const ROLES = {
  ADMIN: 'admin',
  EDITOR: 'editor',
  VIEWER: 'viewer'
};

const PERMISSIONS = {
  UPLOAD_FILE: [ROLES.ADMIN, ROLES.EDITOR],
  LIST_FILES: [ROLES.ADMIN, ROLES.EDITOR, ROLES.VIEWER],
  READ_FILE: [ROLES.ADMIN, ROLES.EDITOR, ROLES.VIEWER],
  DELETE_FILE: [ROLES.ADMIN],
  GENERATE_POLICY: [ROLES.ADMIN, ROLES.EDITOR],
  APPROVE_POLICY: [ROLES.ADMIN, ROLES.EDITOR],
  GENERATE_TOKEN: [ROLES.ADMIN, ROLES.EDITOR],
  VALIDATE_TOKEN: [ROLES.ADMIN, ROLES.EDITOR, ROLES.VIEWER]
};

module.exports = { ROLES, PERMISSIONS };
